import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
// ShopProvider'ı içe aktar
import { ShopProvider } from "@/context/ShopContext";
import Navbar from "@/components/Navbar"; // Navbar'ın varsa ekle

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Veilore App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {/* TÜM UYGULAMAYI BURADA SARMALIYORUZ */}
        <ShopProvider>
          {/* Navbar her sayfada görünsün diye buraya koyabilirsin */}
          <Navbar /> 
          
          {/* Sayfa içerikleri buraya gelir */}
          {children}
        </ShopProvider>
      </body>
    </html>
  );
}